### PR TITLE
Formatting ``

### PR DESCRIPTION
**Pull request by nqthqn**

### CODE REVIEW

**Comment by JoelQ** [comment]
Github doesn't seem to like this because it interprets the pipes in `<|`, `|>`, as part of the table structure. I got around it in the plain text by escaping them with a backslash.

However, GitHub doesn't seem to recognize that a pipe inside backticks is part of the content, not table structure 😞 

Any suggestions on something that formats correctly without breaking the table?

**Comment by nqthqn** [comment]
| test | hello|
|---|---|
|```\|>``` ```<\|```| cool? |


\\|> in ```

**Comment by JoelQ** [comment]
Huh, so triple backticks respects the escape and is treated as inline code inside a table 😮 

Do you want to update your PR to use this style? Currently the preview shows the table layout gets messed up:

elm-javascript-haskell-equivalents 2018-05-31 17-49-00

**Comment by nqthqn** [comment]
If you want to fix with the ```\ that's cool. I don't want to update this PR.

**Pull request closed without merging**
